import { createFileRoute } from "@tanstack/react-router";

import {
  BoundaryBadge,
  MiniSparkbar,
  Stat,
  StatusPill,
} from "@/components/site/control-primitives";
import { mockNoiseMetrics, mockUsageMetrics } from "@/lib/api/mock";

export const Route = createFileRoute("/app/operator")({
  component: OperatorDashboard,
});

function OperatorDashboard() {
  return (
    <div className="space-y-8">
      <header className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <div className="font-mono text-token-2xs uppercase tracking-wider text-mint">
            Operator
          </div>
          <h1 className="mt-1 font-display text-token-2xl font-semibold tracking-tight">
            Usage & value
          </h1>
          <p className="mt-1 max-w-2xl text-token-sm text-muted-foreground">
            High-level deployment health and noise-reduction impact across all installations.
          </p>
        </div>
        <BoundaryBadge boundary="private-api" />
      </header>

      <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
        {mockUsageMetrics.map((m) => (
          <Stat key={m.label} label={m.label} value={m.value} hint={m.delta} />
        ))}
      </section>

      <section className="grid gap-6 lg:grid-cols-2">
        <div className="rounded-token border border-border bg-transparent p-5">
          <h2 className="font-display text-token-lg font-semibold">Noise reduction (14d)</h2>
          <div className="mt-4 space-y-4">
            {mockNoiseMetrics.map((m) => (
              <div key={m.label} className="flex items-center justify-between gap-4">
                <div>
                  <div className="text-token-sm text-foreground/90">{m.label}</div>
                  <div className="font-mono text-token-2xs text-muted-foreground">
                    total {m.value}
                  </div>
                </div>
                <MiniSparkbar values={m.spark} className="w-40" />
              </div>
            ))}
          </div>
        </div>

        <div className="rounded-token border border-border bg-transparent p-5">
          <h2 className="font-display text-token-lg font-semibold">Weekly value report</h2>
          <p className="mt-1 text-token-xs text-muted-foreground">
            Auto-generated summary across installations. Markdown render will be server-side once
            shipped.
          </p>
          <ul className="mt-4 space-y-2 text-token-sm text-foreground/90">
            <li>· 612 PRs preflighted with private context, 87 maintainer comments suppressed.</li>
            <li>· 41 new public-safe packets generated by confirmed miners.</li>
            <li>· 0 incidents from upstream Gittensor drift this week.</li>
            <li>· MCP 0.2.x in use by 84 active miners.</li>
          </ul>
          <div className="mt-4">
            <StatusPill status="ready">Signal · ready</StatusPill>
          </div>
        </div>
      </section>
    </div>
  );
}
